"""
Iterables are the function that contains __iter__ definition (method) to to iterate over the list.

A generator which contains the next function can also contains the __iter__ dunder method to iterate over
the number of the list which are generated by the next function.

__iter__ method allows to iterate over the class.

"""

class FirstHundredGenerator:
    def __init__(self, number, stop):
        self.stop = stop
        self.number = number

    def __next__(self):
        if self.number < self.stop:
            counter = self.number
            self.number += 1
            return counter
        else:
            raise StopIteration
        
    def __iter__(self):
        return self


genz = FirstHundredGenerator(1, 10)

for i in genz:
    print(i)
